package com.mysaasa;

import net.glxn.qrgen.QRCode;
import org.apache.wicket.request.IRequestCycle;
import org.apache.wicket.request.IRequestHandler;
import org.apache.wicket.request.Request;
import org.apache.wicket.request.http.WebResponse;

import java.io.ByteArrayOutputStream;

/**
 * Generates QR Codes for BitCoin orders
 * I'm going to mark this deprecated, it can probably be deleted from this branch
 *
 *
 * Created by adam on 2014-10-21.
 */

@Deprecated
public class QrGenerator implements IRequestHandler {
	private String[] parts;

	public QrGenerator(Request request) {
		String path = request.getClientUrl().getPath();
		parts = path.split("/");

	}

	@Override
	public void respond(IRequestCycle requestCycle) {
		try {
			if (parts.length == 3) {
				String s = "";
				/*
				if (parts[1].equals("order")) {
					Cart cart = OrderService.get().findCartByUid(parts[2]);
					OrderBitcoinInfo bitcoinInfo = BitcoinService.get().getOrderBitcoinInfo(cart);
					BigDecimal amountOwed = cart.calculateBitcoinOwed();
					s = "bitcoin:" + bitcoinInfo.getReceivingAddress() + "?amount=" + amountOwed;
				}
				*/

				WebResponse response = ((WebResponse) requestCycle.getResponse());
				response.setStatus(200);
				ByteArrayOutputStream stream = QRCode.from(s).stream();
				byte[] bytes = stream.toByteArray();
				response.setContentLength(bytes.length);
				response.write(bytes);
				return;
			}

		} catch (Exception e) {
			//e.printStackTrace();;
		}
		WebResponse response = ((WebResponse) requestCycle.getResponse());
		response.setStatus(200);
		ByteArrayOutputStream stream = QRCode.from("This QR Code is Invalid: Generated By Simple Platform. Could not generate QR for Order").stream();
		byte[] bytes = stream.toByteArray();
		response.setContentLength(bytes.length);
		response.write(bytes);

	}

	@Override
	public void detach(IRequestCycle requestCycle) {

	}
}
